FROM node:20-bullseye

# Set the working directory in the container
WORKDIR /app

# Install only necessary packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    && rm -rf /var/lib/apt/lists/*





# Expose the port your app runs on
EXPOSE 4000
#install az cli
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

# Start the app
CMD ["npm", "run", "dev"]